swagger: '2.0'
info:
  description: Dummy service for payments
  version: '1.0'
  title: Payment service

basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /client/{version}/makePayment:
    post:
      summary: Make a payment
      operationId: MakePayment
      parameters:
        - $ref: '#/parameters/version'
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/PaymentRequest'
      responses:
        201:
          description: Payment was successful.
          schema:
            $ref: '#/definitions/PaymentResponse'

definitions:
  PaymentRequest:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      id:
        type: integer
      cardNumber:
        type: string
        description: 'Card number'
        example: '2234532345766632'
        minLength: 12
        maxLength: 19

  PaymentResponse:
    type: object
    properties:
      id:
        type: integer
      status:
        type: string

parameters:
  version:
    name: version
    description: 'API version'
    in: path
    type: string
    required: true